package io.github.gambletan.unifiedchannel;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

import static org.junit.jupiter.api.Assertions.*;

class ServiceBridgeTest {

    private ChannelManager manager;
    private MockAdapter adapter;

    @BeforeEach
    void setUp() {
        manager = new ChannelManager();
        adapter = new MockAdapter("test");
        manager.addChannel(adapter);
    }

    @Test
    void exposeCreatesCommand() {
        var bridge = new ServiceBridge(manager);
        bridge.expose("deploy", args -> "Deployed " + (args.length > 0 ? args[0] : "all"), "Deploy a service");

        var commands = bridge.getCommands();
        assertTrue(commands.containsKey("deploy"));
        assertEquals("Deploy a service", commands.get("deploy").description());
    }

    @Test
    void helpCommandAutoGenerated() {
        var bridge = new ServiceBridge(manager);
        bridge.expose("status", args -> "OK", "Check status");

        var commands = bridge.getCommands();
        assertTrue(commands.containsKey("help"));
        assertTrue(commands.containsKey("status"));
    }

    @Test
    void helpCommandListsAllCommands() throws Exception {
        var bridge = new ServiceBridge(manager);
        bridge.expose("deploy", args -> "done", "Deploy service");
        bridge.expose("restart", args -> "restarted", "Restart service");

        adapter.connect().get();

        // Simulate /help command
        adapter.simulateInbound(UnifiedMessage.builder()
                .channelId("test")
                .sender(new Identity("u1"))
                .chatId("c1")
                .content(MessageContent.text("/help"))
                .build());

        // Help is handled by command middleware; check that it doesn't reach terminal listener
        Thread.sleep(200);
    }

    @Test
    void exposedCommandHandlesMessage() throws Exception {
        var bridge = new ServiceBridge(manager);
        bridge.expose("ping", args -> "pong!", "Ping check");

        adapter.connect().get();

        adapter.simulateInbound(UnifiedMessage.builder()
                .channelId("test")
                .sender(new Identity("u1"))
                .chatId("c1")
                .content(MessageContent.text("/ping"))
                .build());

        Thread.sleep(200);
        // Command was handled by the bridge (via CommandMiddleware)
    }

    @Test
    void exposeAsyncCommand() throws Exception {
        var bridge = new ServiceBridge(manager);
        bridge.exposeAsync("slow", args ->
                        CompletableFuture.supplyAsync(() -> "async result"),
                "Slow async command");

        adapter.connect().get();
        assertTrue(bridge.getCommands().containsKey("slow"));
    }

    @Test
    void exposeStatus() {
        var bridge = new ServiceBridge(manager);
        bridge.exposeStatus(() -> "All systems operational");

        assertTrue(bridge.getCommands().containsKey("status"));
        assertEquals("Show service status", bridge.getCommands().get("status").description());
    }

    @Test
    void exposeLogs() {
        var bridge = new ServiceBridge(manager);
        bridge.exposeLogs(args -> "Log line 1\nLog line 2");

        assertTrue(bridge.getCommands().containsKey("logs"));
        assertEquals("View recent logs", bridge.getCommands().get("logs").description());
    }

    @Test
    void customPrefix() {
        var bridge = new ServiceBridge(manager, "!");
        bridge.expose("ban", args -> "banned", "Ban user");

        assertEquals("!", bridge.getPrefix());
        assertTrue(bridge.getCommands().containsKey("ban"));
    }

    @Test
    void getManagerReturnsOriginal() {
        var bridge = new ServiceBridge(manager);
        assertSame(manager, bridge.getManager());
    }

    @Test
    void chainingWorks() {
        var bridge = new ServiceBridge(manager)
                .expose("a", args -> "a", "Command A")
                .expose("b", args -> "b", "Command B")
                .exposeStatus(() -> "OK")
                .exposeLogs(args -> "logs");

        assertEquals(5, bridge.getCommands().size()); // help + a + b + status + logs
    }

    // Mock adapter (same pattern as ChannelManagerTest)
    static class MockAdapter implements ChannelAdapter {
        final String id;
        final java.util.List<Consumer<UnifiedMessage>> listeners = new CopyOnWriteArrayList<>();
        volatile ChannelStatus status;

        MockAdapter(String id) {
            this.id = id;
            this.status = ChannelStatus.disconnected(id);
        }

        @Override public String channelId() { return id; }

        @Override
        public CompletableFuture<Void> connect() {
            status = ChannelStatus.connected(id);
            return CompletableFuture.completedFuture(null);
        }

        @Override
        public CompletableFuture<Void> disconnect() {
            status = ChannelStatus.disconnected(id);
            return CompletableFuture.completedFuture(null);
        }

        @Override
        public void onMessage(Consumer<UnifiedMessage> listener) { listeners.add(listener); }

        @Override
        public CompletableFuture<Void> send(OutboundMessage message) {
            return CompletableFuture.completedFuture(null);
        }

        @Override
        public ChannelStatus getStatus() { return status; }

        void simulateInbound(UnifiedMessage msg) {
            for (var l : listeners) l.accept(msg);
        }
    }
}
